# Generated by Django 2.2 on 2021-06-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客网站', 'verbose_name_plural': '博客网站'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='db_article',
        ),
    ]
