# Generated by Django 2.2 on 2021-06-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_brief_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['publish_date'], 'verbose_name': '博客网站', 'verbose_name_plural': '博客网站'},
        ),
    ]
