# Generated by Django 2.2 on 2021-06-19 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210617_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'tb_category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory'),
            preserve_default=False,
        ),
    ]
