# Generated by Django 2.2 on 2021-07-17 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='DB_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '模块名称',
                'verbose_name_plural': '模块名称',
                'db_table': 'db_module',
            },
        ),
        migrations.CreateModel(
            name='DB_testcase',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用例编号')),
                ('t_priority', models.CharField(max_length=100, verbose_name='优先级')),
                ('t_purpose', models.CharField(max_length=100, verbose_name='测试目的')),
                ('t_precondition', models.CharField(max_length=100, verbose_name='前置条件')),
                ('t_steps', models.CharField(max_length=100, verbose_name='测试步骤')),
                ('t_expected_result', models.CharField(max_length=100, verbose_name='预期结果')),
                ('t_actual_result', models.CharField(max_length=100, verbose_name='实际结果')),
                ('t_remark', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('t_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.DB_module', verbose_name='模块名称')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'db_testcase',
                'ordering': ['t_id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='CaseManagement.ArticleCategory')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'tb_article',
                'ordering': ('created',),
            },
        ),
    ]
