# Generated by Django 2.2 on 2021-06-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_testcase',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用例编号')),
                ('t_module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('t_priority', models.CharField(max_length=100, verbose_name='优先级')),
                ('t_purpose', models.CharField(max_length=100, verbose_name='测试目的')),
                ('t_precondition', models.CharField(max_length=100, verbose_name='前置条件')),
                ('t_steps', models.CharField(max_length=100, verbose_name='测试步骤')),
                ('t_expected_result', models.CharField(max_length=100, verbose_name='预期结果')),
                ('t_actual_result', models.CharField(max_length=100, verbose_name='实际结果')),
                ('t_remark', models.CharField(max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'db_testcase',
            },
        ),
    ]
