# Generated by Django 2.2 on 2021-06-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_testcase',
            name='fk_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.DB_module'),
        ),
    ]
