# Generated by Django 2.2 on 2021-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_testcase',
            options={'ordering': ['t_priority'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.RemoveField(
            model_name='db_testcase',
            name='t_id',
        ),
        migrations.AddField(
            model_name='db_testcase',
            name='id',
            field=models.AutoField(auto_created=True, default=111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
