# Generated by Django 2.2 on 2021-06-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_testcase',
            options={'ordering': ['t_id'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
    ]
