# Generated by Django 2.2 on 2021-07-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0002_auto_20210725_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_testcase',
            name='t_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.DB_module', verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='db_testcase',
            name='t_remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
